User Registration and login setup
dhmit/paris_1970 pull request #179
Opened 2022-07-12 15:53 UTC by Nisha-Nathan

I made a signup feature that allows users to register and be assigned specific permissions that allow them to add, edit or remove blog posts in the admin panel. I also made a login feature that can be used by both the user and admin to access the admin page with different levels of permissions. Lastly, I redirected the log-out URL in the admin page to the home page of the site instead of the default page that prompts login again.

2022-07-13 19:23 UTC, anastasia commented
I believe there are some requirements missing from requirements.txt (django-crispy-forms and crispy-bootstrap5). Thanks for the note about installing!

2022-07-13 19:29 UTC, anastasia requested changes

2022-07-13 19:29 UTC, anastasia commented on backend/blog/migrations/0003_auto_20220713_1105.py
> +
Great, thanks for adding this!

2022-07-13 19:29 UTC, anastasia commented on backend/blog/views.py
> +    if request.method == "POST":
Hey – we should talk about this. This actually opens us up to anyone being able to register and therefore add/delete/edit blog posts. This is very dangerous! I appreciate all the effort that you put in this PR. 
Like we talked with @ADJohnson314 I think Django does a really great job with the bare bones registration that exists already. I was expecting only some permissions settings, which you're doing on any new user registration, but you're also doing so much more! Great exploration but I think this means we need to rethink our set up.

2022-07-18 16:02 UTC, anastasia commented on backend/config/urls.py
> +    path('login/',auth_views.LoginView.as_view(template_name='admin/login.html'),name='login'),
great!

2022-07-18 20:26 UTC, Nisha-Nathan commented on backend/app/migrations/0002_auto_20220718_1614.py
> +def permissions_func(apps, _):
great!

2022-07-19 16:35 UTC, merged